var $ = require('jquery')(window);
global.jQuery = require("jquery");
window.angular = require('angular');
var bootstrap = require('bootstrap');
var ngTagsInput = require('ng-tags-input');
var ngTagInputCss = require('./node_modules/ng-tags-input/build/ng-tags-input.min.css');
var ngTagInputBootstrapCss = require('./node_modules/ng-tags-input/build/ng-tags-input.bootstrap.min.css');
var bootstrapCss = require('./node_modules/bootstrap/dist/css/bootstrap.min.css');
var fontAwesome = require('./node_modules/font-awesome/css/font-awesome.min.css');