angular.module('todoApp', 
    ['ngTagsInput',
     'angular-rating-icons',
     'ds.clock',
     'angAccordion', 
     'ui.bootstrap', 
     'daterangepicker',
     'angular-advanced-searchbox',
     'angularMoment'
    ]);